# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=32)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='commercial_sector',
            field=models.CharField(default='Todos', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.EmailField(choices=[('T', 'True'), ('F', 'False')], default='T', max_length=70),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(to='promoapp_business.Product'),
        ),
    ]
