# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 16:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_business', '0003_auto_20170609_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='name',
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
