# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_business', '0004_auto_20170609_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingcampaign',
            name='start_date',
            field=models.DateField(),
        ),
    ]
