# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_user', '0012_auto_20170622_1234'),
        ('promoapp_business', '0005_auto_20170621_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadvertisingcampaign',
            name='advertisingcampaign',
        ),
        migrations.RemoveField(
            model_name='companyadvertisingcampaign',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyadvertisingcampaign',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='company',
            name='advertisingcampaigns',
        ),
        migrations.DeleteModel(
            name='AdvertisingCampaign',
        ),
        migrations.DeleteModel(
            name='CompanyAdvertisingCampaign',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
