# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_campaign', '0002_auto_20170623_1228'),
        ('promoapp_business', '0006_auto_20170622_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='advertisingcampaigns',
            field=models.ManyToManyField(to='promoapp_campaign.AdvertisingCampaign'),
        ),
    ]
