# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_business', '0008_auto_20170623_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='commercial_sector',
            field=models.CharField(max_length=32),
        ),
    ]
