# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_business', '0009_auto_20170628_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(),
        ),
    ]
