# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_campaign', '0004_auto_20170705_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingcampaign',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promoapp_user.PromotionManager'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promoapp_user.PromotionManager'),
        ),
    ]
