# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_user', '0003_promotionmanager_storemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionmanager',
            name='user_type',
            field=models.CharField(default='Promotion Manager', max_length=200),
        ),
        migrations.AlterField(
            model_name='storemanager',
            name='user_type',
            field=models.CharField(default='Store Manager', max_length=200),
        ),
    ]
