# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_user', '0004_auto_20170602_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionmanager',
            name='is_active',
            field=models.CharField(default='true', max_length=200),
        ),
        migrations.AddField(
            model_name='storemanager',
            name='is_active',
            field=models.CharField(default='true', max_length=200),
        ),
    ]
