# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_user', '0005_auto_20170606_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionmanager',
            name='is_active',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='T', max_length=200),
        ),
        migrations.AlterField(
            model_name='storemanager',
            name='is_active',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='T', max_length=200),
        ),
    ]
