# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_user', '0006_auto_20170609_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanager',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
