# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_business', '0004_auto_20170609_1226'),
        ('promoapp_user', '0008_promotionmanager_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemanager',
            name='stores',
            field=models.ManyToManyField(to='promoapp_business.Store'),
        ),
    ]
