# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_user', '0010_user_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionmanager',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='acc_type',
            field=models.CharField(choices=[('FB', 'Facebook'), ('G', 'Google'), ('TW', 'Twitter')], default='FB', max_length=200),
        ),
    ]
