# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp_user', '0011_auto_20170615_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionmanager',
            name='promotions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='promotions',
        ),
    ]
